---
title: "Sentiment Analysis"
author: "Muhammad Apriandito"
---

# Install Packages

```{r}
# Install Packages
install.packages(c("tidyverse",
                   "textclean", 
                   "lubridate", 
                   "vader"))
```

# Load Packages

```{r}
# Load Library
library(tidyverse)
library(textclean)
library(lubridate)
library(vader)
```

# Load Data

```{r message=FALSE, warning=FALSE}
# Load Data
df <- read_rds("data/tweet_dc.rds")
```

```{r}
# Melihat 5 baris pertama data
head(df, 5)
```

# Text Cleaning

```{r}
# Text Cleaning
df_clean <- df %>%
  mutate(created_at = as_date(created_at)) %>%
  filter(created_at > dmy("25-12-2020")) %>%
  select(text) %>%
  mutate(text = strip(text)) %>%
  mutate(text = replace_emoji(text)) %>%
  mutate(text = replace_html(text)) %>%
  mutate(text = replace_hash(text, pattern = "#([A-Za-z0-9_]+)", replacement = "")) %>%
  mutate(text = replace_tag(text, pattern = "@([A-Za-z0-9_]+)", replacement = ""))
```

# Analisis Sentiment

```{r}
# Analisis sentiment
sentiment <- vader_df(df_clean$text)
```

# Visualisasi Sentiment

```{r}
# Visualisasi Sentiment
visualisasi_sentiment <- sentiment %>%
  mutate(sentiment = case_when(
    compound >= 0 ~ "positive",
    compound < 0 ~ "negative"
  )) %>%
  group_by(sentiment) %>%
  count() %>%
  drop_na() %>%
  ggplot(aes(x = sentiment, y = n, fill = sentiment)) +
  geom_col() +
  labs(
    title = "Sentiment Analysis: Digital Currency",
    y = "Jumlah Tweet",
    x = "",
    fill = "Sentiment"
  ) +
  theme_minimal()

visualisasi_sentiment
```

```{r}
# Menyimpan hasil visualisasi sentiment
ggsave(visualisasi_sentiment,
  filename = "plot/sentiment.png",
  width = 15,
  height = 15,
  dpi = 300,
  type = "cairo",
  units = "cm",
  limitsize = FALSE
)
```
