---
title: "Topic Modelling"
author: "Muhammad Apriandito"
---

```{r}
# Load Library
library(tidyverse)
library(tm)
library(lda)
library(LDAvis)
```

```{r}
# Load Data
df <- read_rds("data/tweet_dc.rds")
```

```{r}
# Text Prepocessing
df_clean <- df %>%
  mutate(created_at = as_date(created_at)) %>%
  filter(created_at > dmy("25-12-2020")) %>%
  select(text) %>%
  mutate(text = strip(text)) %>%
  mutate(text = replace_emoji(text)) %>%
  mutate(text = replace_html(text)) %>%
  mutate(text = replace_hash(text, pattern = "#([A-Za-z0-9_]+)", replacement = "")) %>%
  mutate(text = replace_tag(text, pattern = "@([A-Za-z0-9_]+)", replacement = "")) %>%
  drop_na()
```

```{r}
tweet <- df_clean$text
```

```{r}
stop_words <- stopwords("SMART")
```

```{r}
# tokenize on space and output as a list:
doc.list <- strsplit(tweet, "[[:space:]]+")

# compute the table of terms:
term.table <- table(unlist(doc.list))
term.table <- sort(term.table, decreasing = TRUE)

# remove terms that are stop words or occur fewer than 5 times:
del <- names(term.table) %in% stop_words | term.table < 5
term.table <- term.table[!del]
vocab <- names(term.table)

# now put the documents into the format required by the lda package:
get.terms <- function(x) {
  index <- match(x, vocab)
  index <- index[!is.na(index)]
  rbind(as.integer(index - 1), as.integer(rep(1, length(index))))
}
documents <- lapply(doc.list, get.terms)
```

```{r}
# Compute some statistics related to the data set:
D <- length(documents)  # number of documents (2,000)
W <- length(vocab)  # number of terms in the vocab (14,568)
doc.length <- sapply(documents, function(x) sum(x[2, ]))  # number of tokens per document [312, 288, 170, 436, 291, ...]
N <- sum(doc.length)  # total number of tokens in the data (546,827)
term.frequency <- as.integer(term.table)
```

```{r}
# MCMC and model tuning parameters:
K <- 2
G <- 5000
alpha <- 0.02
eta <- 0.02

fit <- lda.collapsed.gibbs.sampler(documents = documents, K = K, vocab = vocab, 
                                   num.iterations = G, alpha = alpha, 
                                   eta = eta, initial = NULL, burnin = 0,
                                   compute.log.likelihood = TRUE)
```

```{r}
theta <- t(apply(fit$document_sums + alpha, 2, function(x) x/sum(x)))
phi <- t(apply(t(fit$topics) + eta, 2, function(x) x/sum(x)))
```

```{r}
topic <- list(phi = phi,
                     theta = theta,
                     doc.length = doc.length,
                     vocab = vocab,
                     term.frequency = term.frequency)
```

```{r}
topic$term.frequency
```


```{r}
# create the JSON object to feed the visualization:
json <- createJSON(phi = topic$phi, 
                   theta = topic$theta, 
                   doc.length = topic$doc.length, 
                   vocab = topic$vocab, 
                   term.frequency = topic$term.frequency)
```

```{r}
serVis(json, out.dir = 'vis', open.browser = TRUE)
```

